# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "imx-device-attestation"
BBFILE_PATTERN_imx-device-attestation := "^${LAYERDIR}/"
BBFILE_PRIORITY_imx-device-attestation = "8"

LAYERSERIES_COMPAT_imx-device-attestation = "walnascar"