# Overrides for HAB and AHAB
OVERRIDES:append:mx6-generic-bsp = ":hab4"
OVERRIDES:append:mx7-generic-bsp = ":hab4"
OVERRIDES:append:mx8m-generic-bsp = ":hab4"
OVERRIDES:append:mx8ulp-generic-bsp = ":ahab"
OVERRIDES:append:mx8qm-generic-bsp = ":ahab"
OVERRIDES:append:mx8qxp-generic-bsp = ":ahab"
OVERRIDES:append:mx8dxl-generic-bsp = ":ahab"
OVERRIDES:append:mx9-generic-bsp = ":ahab"

# Select signed target based on device
SIGNED_TARGET:mx6-generic-bsp = "u-boot"
SIGNED_TARGET:mx7-generic-bsp = "u-boot"
SIGNED_TARGET:mx8m-generic-bsp = "flash_evk"
SIGNED_TARGET:mx8qm-generic-bsp = "flash_spl"
SIGNED_TARGET:mx8qxp-generic-bsp = "flash_spl"
SIGNED_TARGET:mx8dxl-generic-bsp = "flash_spl"
SIGNED_TARGET:mx8ulp-generic-bsp = "flash_singleboot_m33"
SIGNED_TARGET:mx91-generic-bsp = "flash_singleboot"
SIGNED_TARGET:mx93-generic-bsp = "flash_singleboot"
SIGNED_TARGET:mx943-generic-bsp = "flash_all"
SIGNED_TARGET:mx95-generic-bsp = "flash_all"
SIGNED_TARGET:mx952-generic-bsp = "flash_all"

# SPSDK family name mapping for AHAB devices
SPSDK_FAMILY:mx8qm-generic-bsp = "mimx8qm"
SPSDK_FAMILY:mx8qxp-generic-bsp = "mimx8qxp"
SPSDK_FAMILY:mx8dxl-generic-bsp = "mimx8dxl"
SPSDK_FAMILY:mx8ulp-generic-bsp = "mimx8ulp"
SPSDK_FAMILY:mx91-generic-bsp = "mimx9131"
SPSDK_FAMILY:mx93-generic-bsp = "mimx9352"
SPSDK_FAMILY:mx943-generic-bsp = "mimx943"
SPSDK_FAMILY:mx95-generic-bsp = "mimx9596"
SPSDK_FAMILY:mx952-generic-bsp = "mimx95294"
