# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "imx-smw-apps"
BBFILE_PATTERN_imx-smw-apps := "^${LAYERDIR}/"
BBFILE_PRIORITY_imx-smw-apps = "8"

LAYERSERIES_COMPAT_imx-smw-apps = "walnascar"
